try {
    console.log($g);
} catch (err) {
    console.error(err);
}